name: Quem
version: '${version}'
main: com.tksimeji.quem.Quem
api-version: '1.21'
depend:
  - Visualkit
commands:
  quem:
    description: Command set for quem.
    usage: /quem <subcommand> [args...]